all:
  children:
    cassandra_nodes:
      hosts:
        cassandra_node1:
          ansible_host: ec2-13-235-54-3.ap-south-1.compute.amazonaws.com
        cassandra_node2:
          ansible_host: ec2-13-205-18-57.ap-south-1.compute.amazonaws.com
        cassandra_node3:
          ansible_host: ec2-3-110-61-31.ap-south-1.compute.amazonaws.com
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/Downloads/Mongodb.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        cassandra_data_dir: /var/lib/cassandra/data
        
    central_server:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        backup_base_dir: /home/shubhraksi246/backup_cassandra
        log_dir: /home/shubhraksi246/cassandra_backup_logs
        retention_days_nodes: 2
        retention_days_central: 7
